# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqefmVMxu913T8zpoxph5esnJ9YBKdiQ
"""

import numpy as np
from collections import Counter

# 1. Logistic Regression
class LogisticRegressionFromScratch:
    def __init__(self, lr=0.01, iterations=1000):
        self.lr = lr
        self.iterations = iterations
        self.weights = None
        self.bias = None

    def _sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.iterations):
            linear_model = np.dot(X, self.weights) + self.bias
            y_predicted = self._sigmoid(linear_model)
            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / n_samples) * np.sum(y_predicted - y)
            self.weights -= self.lr * dw
            self.bias -= self.lr * db

    def predict(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        y_predicted = self._sigmoid(linear_model)
        return [1 if i > 0.5 else 0 for i in y_predicted]

# 2. Decision Tree (Simplified)
class DecisionTreeFromScratch:
    def __init__(self, max_depth=10):
        self.max_depth = max_depth
        self.tree = None

    def fit(self, X, y):
        self.tree = self._build_tree(X, y)

    def _entropy(self, y):
        hist = np.bincount(y)
        ps = hist / len(y)
        return -np.sum([p * np.log2(p) for p in ps if p > 0])

    def _build_tree(self, X, y, depth=0):
        n_samples, n_feats = X.shape
        n_labels = len(np.unique(y))
        if depth >= self.max_depth or n_labels == 1:
            return Counter(y).most_common(1)[0][0]

        feat_idxs = np.random.choice(n_feats, n_feats, replace=False)
        best_feat, best_thresh = self._best_split(X, y, feat_idxs)
        left_idxs, right_idxs = self._split(X[:, best_feat], best_thresh)
        left = self._build_tree(X[left_idxs, :], y[left_idxs], depth+1)
        right = self._build_tree(X[right_idxs, :], y[right_idxs], depth+1)
        return {'feat': best_feat, 'thresh': best_thresh, 'left': left, 'right': right}

    def _best_split(self, X, y, feat_idxs):
        best_gain = -1
        split_idx, split_thresh = None, None
        for feat_idx in feat_idxs:
            X_column = X[:, feat_idx]
            thresholds = np.unique(X_column)
            for threshold in thresholds:
                gain = self._information_gain(y, X_column, threshold)
                if gain > best_gain:
                    best_gain = gain
                    split_idx = feat_idx
                    split_thresh = threshold
        return split_idx, split_thresh

    def _information_gain(self, y, X_column, threshold):
        parent_entropy = self._entropy(y)
        left_idxs, right_idxs = self._split(X_column, threshold)
        if len(left_idxs) == 0 or len(right_idxs) == 0: return 0
        n = len(y)
        n_l, n_r = len(left_idxs), len(right_idxs)
        e_l, e_r = self._entropy(y[left_idxs]), self._entropy(y[right_idxs])
        child_entropy = (n_l/n) * e_l + (n_r/n) * e_r
        return parent_entropy - child_entropy

    def _split(self, X_column, split_thresh):
        left_idxs = np.argwhere(X_column <= split_thresh).flatten()
        right_idxs = np.argwhere(X_column > split_thresh).flatten()
        return left_idxs, right_idxs

    def predict(self, X):
        return np.array([self._traverse_tree(x, self.tree) for x in X])

    def _traverse_tree(self, x, node):
        if not isinstance(node, dict): return node
        if x[node['feat']] <= node['thresh']:
            return self._traverse_tree(x, node['left'])
        return self._traverse_tree(x, node['right'])

# 3. K-Nearest Neighbors (KNN)
class KNNFromScratch:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        return np.array([self._predict(x) for x in X])

    def _predict(self, x):
        distances = [np.sqrt(np.sum((x - x_train)**2)) for x_train in self.X_train]
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]
        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]

# 4. Support Vector Classifier (Linear SVM via Hinge Loss)
class SVCFromScratch:
    def __init__(self, lr=0.001, lambda_param=0.01, iterations=1000):
        self.lr = lr
        self.lambda_param = lambda_param
        self.iterations = iterations
        self.w = None
        self.b = None

    def fit(self, X, y):
        y_ = np.where(y <= 0, -1, 1)
        n_samples, n_features = X.shape
        self.w = np.zeros(n_features)
        self.b = 0

        for _ in range(self.iterations):
            for idx, x_i in enumerate(X):
                condition = y_[idx] * (np.dot(x_i, self.w) - self.b) >= 1
                if condition:
                    self.w -= self.lr * (2 * self.lambda_param * self.w)
                else:
                    self.w -= self.lr * (2 * self.lambda_param * self.w - np.dot(x_i, y_[idx]))
                    self.b -= self.lr * y_[idx]

    def predict(self, X):
        approx = np.dot(X, self.w) - self.b
        return np.sign(approx)

# 5. Multinomial Naive Bayes
class MultinomialNBFromScratch:
    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.classes = np.unique(y)
        n_classes = len(self.classes)
        self.phi = np.zeros(n_classes)
        self.theta = np.zeros((n_classes, n_features))

        for i, c in enumerate(self.classes):
            X_c = X[y == c]
            self.phi[i] = X_c.shape[0] / n_samples
            self.theta[i, :] = (np.sum(X_c, axis=0) + 1) / (np.sum(X_c) + n_features)

    def predict(self, X):
        return [self.classes[np.argmax(self._log_likelihood(x))] for x in X]

    def _log_likelihood(self, x):
        return np.log(self.phi) + np.sum(x * np.log(self.theta), axis=1)

# 6. Random Forest
class RandomForestFromScratch:
    def __init__(self, n_trees=10, max_depth=10):
        self.n_trees = n_trees
        self.max_depth = max_depth
        self.trees = []

    def fit(self, X, y):
        for _ in range(self.n_trees):
            tree = DecisionTreeFromScratch(max_depth=self.max_depth)
            idx = np.random.choice(len(X), len(X), replace=True)
            tree.fit(X[idx], y[idx])
            self.trees.append(tree)

    def predict(self, X):
        tree_preds = np.array([tree.predict(X) for tree in self.trees])
        return [Counter(tree_preds[:, i]).most_common(1)[0][0] for i in range(len(X))]

# 7. AdaBoost (Simplified Binary)
class AdaBoostFromScratch:
    def __init__(self, n_clf=5):
        self.n_clf = n_clf
        self.clfs = []

    def fit(self, X, y):
        n_samples, _ = X.shape
        w = np.full(n_samples, (1 / n_samples))
        y_ = np.where(y == 0, -1, 1)

        for _ in range(self.n_clf):
            clf = DecisionTreeFromScratch(max_depth=1) # Decision Stump
            clf.fit(X, y)
            predictions = np.where(clf.predict(X) == 0, -1, 1)
            error = sum(w[predictions != y_])
            EPS = 1e-10
            alpha = 0.5 * np.log((1.0 - error + EPS) / (error + EPS))
            w *= np.exp(-alpha * y_ * predictions)
            w /= np.sum(w)
            self.clfs.append((clf, alpha))

    def predict(self, X):
        clf_preds = [alpha * np.where(clf.predict(X) == 0, -1, 1) for clf, alpha in self.clfs]
        y_pred = np.sum(clf_preds, axis=0)
        return np.where(np.sign(y_pred) == -1, 0, 1)

# 8. Gradient Boosting (Regression-based structure)
class GradientBoostingFromScratch:
    def __init__(self, n_estimators=10, lr=0.1, max_depth=3):
        self.n_estimators = n_estimators
        self.lr = lr
        self.max_depth = max_depth
        self.trees = []

    def fit(self, X, y):
        self.f0 = np.mean(y)
        f_m = np.full(len(y), self.f0)
        for _ in range(self.n_estimators):
            residuals = y - f_m
            tree = DecisionTreeFromScratch(max_depth=self.max_depth)
            # Mocking regression behavior for simplicity
            tree.fit(X, residuals.astype(int))
            self.trees.append(tree)
            f_m += self.lr * tree.predict(X)

    def predict(self, X):
        y_pred = np.full(len(X), self.f0)
        for tree in self.trees:
            y_pred += self.lr * tree.predict(X)
        return y_pred